---
# TODO: There has to be a better way to specify to run as clojars for this whole role
# System
- name: ensure clojars group exists
  group: name=clojars state=present system=yes
  become: yes

# TODO: should we make sure that 
- name: "ensure clojars user exists"
  become: yes
  become_user: root
  user: name=clojars password=clojars shell=/bin/false #TODO: change password! #TODO: check if we can turn off shell for this user

- include: files.yml
  become_user: clojars
  become: yes

# Install software
- name: install software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - unzip
    - cronolog
    - sqlite3
    - python-lxml

# - name: install cronolog
#   apt: name=cronolog state=present
#   become: yes
#
# - name: install sqlite
#   apt: name=sqlite3 state=present
#   become: yes
#
# # Install lxml, required for Maven ansible module
# - name: install lxml
#   apt: name=python-lxml state=present
#   become: yes

# TODO: waiting on https://github.com/ansible/ansible-modules-extras/issues/1452 to use ~ instead of /home/clojars
- maven_artifact:
    group_id=org.apache.maven.indexer
    artifact_id="indexer-core"
    version={{ indexer_version }}
    classifier=cli
    dest="/home/clojars/indexer/indexer-core-{{ indexer_version }}-cli.jar"
  become: yes
  become_user: clojars


# Run DB migrations, where do we get clojars.sql from?


# Build and run Clojars

- name: start clojars
  service: name=clojars state=started

- name: build clojars
  become: yes
  become_user: clojars
  script: build-clojars "{{clojars_version}}"
  args:
    creates: "/home/clojars/releases/clojars-web-{{clojars_version}}-standalone.jar"

- name: deploy clojars
  script: deploy-clojars "{{clojars_version}}" "{{yeller_api_key}}"
  become: yes
  become_user: clojars
  args:
    creates: "" # TODO: check the symlink for idempotence
  notify: restart clojars

- include: cron.yml
- include: nginx.yml
  become: yes