---
# TODO: There has to be a better way to specify to run as clojars for this whole role
# System
- name: ensure clojars group exists
  group: name=clojars state=present system=yes
  become: yes

# TODO: should we make sure that 
- name: "ensure clojars user exists"
  become: yes
  become_user: root
  user: name=clojars shell=/bin/bash #TODO: check if we can turn off shell for this user

- include: files.yml
  become_user: clojars
  become: yes
  notify: restart clojars

# Install software
- name: install software required for Clojars
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - unzip
    - cronolog
    - sqlite3
    - python-lxml

# TODO: waiting on https://github.com/ansible/ansible-modules-extras/issues/1452 to use ~ instead of /home/clojars
- maven_artifact:
    group_id=org.apache.maven.indexer
    artifact_id="indexer-core"
    version={{ indexer_version }}
    classifier=cli
    dest="/home/clojars/indexer/indexer-core-{{ indexer_version }}-cli.jar"
  become: yes
  become_user: clojars

# Build and run Clojars

- name: TEMP copy clojars JAR
  copy: src=clojars-web-{{clojars_version}}-standalone.jar dest="/home/clojars/releases"
  become: yes
  become_user: clojars


- name: build clojars
  become: yes
  become_user: clojars
  script: build-clojars "{{clojars_version}}"
  args:
    creates: "/home/clojars/releases/clojars-web-{{clojars_version}}-standalone.jar"

- name: deploy clojars
  script: deploy-clojars "{{clojars_version}}" "{{yeller_api_key}}" "{{yeller_env}}"
  become: yes
  become_user: root
  args:
    creates: "" # TODO: check the symlink for idempotence

- name: migrate db
  script: migrate-db
  become: yes
  become_user: clojars

- name: start clojars
  service: name=clojars state=started

- include: cron.yml

- include: nginx.yml
  become: yes