---
- name: add nginx ppa
  become: yes
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: install nginx
  apt: pkg=nginx state=installed
- name: ensure nginx is enabled
  service: name=nginx state=started enabled=yes
  become: yes
  become_user: root

- name: ensure nginx conf exists
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx
# TODO: should this be an nginx restart?

- name: ensure nginx clojars conf exists
  template: src=clojars.nginx.conf.j2 dest=/etc/nginx/sites-enabled/clojars
  notify: reload nginx

- name: truncate default nginx conf
  copy: dest=/etc/nginx/sites-enabled/default content='' force=yes
  notify: reload postfix

- file: path={{ nginx_ssl_conf_dir }} state=directory mode=0700

- name: ensure /var/log/nginx is world readable
  file: path=/var/log/nginx mode=0755

- name: ensure proper nginx lograte config exists
  template: src=logrotate-nginx.j2 dest=/etc/logrotate.d/nginx
  
# TODO: parameterise this copy into one task with variables and a loop.
# TODO: if these change we want to reload nginx config
- copy: src="{{ nginx_private_ssl_dir }}/clojars.org.crt" dest={{ nginx_ssl_conf_dir }}
- copy: src="{{ nginx_private_ssl_dir }}/clojars.org.csr" dest={{ nginx_ssl_conf_dir }}
- copy: src="{{ nginx_private_ssl_dir }}/clojars.org.key" dest={{ nginx_ssl_conf_dir }} mode=0640 # VERY IMPORTANT THIS IS ONLY READABLE BY ROOT!!!!
- copy: src="{{ nginx_private_ssl_dir }}/dhparams-1024.pem" dest={{ nginx_ssl_conf_dir }}
- copy: src="{{ nginx_private_ssl_dir }}/dhparams-2048.pem" dest={{ nginx_ssl_conf_dir }}
- copy: src="{{ nginx_private_ssl_dir }}/sub.class1.server.ca.pem" dest={{ nginx_ssl_conf_dir }}
