---
- name: add nginx ppa
  become: yes
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: install nginx
  apt: pkg=nginx state=installed

- name: ensure nginx is enabled
  service: name=nginx state=started enabled=yes
  become: yes
  become_user: root

- name: ensure nginx conf exists
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: ensure nginx clojars conf exists
  template: src=clojars.nginx.conf.j2 dest=/etc/nginx/sites-enabled/clojars
  notify: reload nginx

- name: truncate default nginx conf
  copy: dest=/etc/nginx/sites-enabled/default content='' force=yes
  notify: reload postfix

- file: path={{ nginx_ssl_conf_dir }} state=directory mode=0700

# TODO: parameterise this copyv into one task with variables and a loop.
- copyv: src="{{ nginx_private_ssl_dir }}/clojars.org.crt" dest={{ nginx_ssl_conf_dir }}
- copyv: src="{{ nginx_private_ssl_dir }}/clojars.org.csr" dest={{ nginx_ssl_conf_dir }}
- copyv: src="{{ nginx_private_ssl_dir }}/clojars.org.key" dest={{ nginx_ssl_conf_dir }} mode=0640 # VERY IMPORTANT THIS IS ONLY READABLE BY ROOT!!!!
- copyv: src="{{ nginx_private_ssl_dir }}/dhparams-1024.pem" dest={{ nginx_ssl_conf_dir }}
- copyv: src="{{ nginx_private_ssl_dir }}/dhparams-2048.pem" dest={{ nginx_ssl_conf_dir }}
- copyv: src="{{ nginx_private_ssl_dir }}/sub.class1.server.ca.pem" dest={{ nginx_ssl_conf_dir }}
