---
- hosts: local
  roles:
#     - { role: clojars, become_user: clojars } TODO: is this a better way to do it?
    - { role: system, become: yes }
    - clojars
  vars_files:
    - private/vars.yml
