---
- hosts: "{{ host }}" 
  remote_user: ec2-user
  become: true
  become_user: root
  vars_files:
    - ../private/vars.yml

  roles:
    - system
    - correttojdk-8
    - leiningen
    - clojars
  
