
# TODO: hardening, fail2ban, firewall, etc
# http://practicalops.com/tag/ansible.html
# http://lattejed.com/first-five-and-a-half-minutes-on-a-server-with-ansible
# http://ryaneschinger.com/blog/securing-a-server-with-ansible/
# https://github.com/vitalk/ansible-secure-ssh
# http://debops.org
# http://blog.mailgun.com/security-guide-basic-infrastructure-security/

- name: update sshd config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart sshd

- name: install custom fail2ban config
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local

- name: Adjust APT update intervals
  template: src=apt_periodic.j2 dest=/etc/apt/apt.conf.d/10periodic

# Do this first to make sure we don't get locked out by the default deny
- name: Allow ssh traffic but limit brute force attempts
  ufw: rule=limit port={{ ubuntu_common_ssh_port }} proto=tcp

- name: Setup ufw default deny
  ufw: state=enabled policy=deny

- name: Allow other traffic
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - smtp
    - http
    - https
    #- rsync

- name: Allow mosh traffic
  ufw: rule=allow proto=udp port={{ ubuntu_common_mosh_from_port }}:{{ ubuntu_common_mosh_to_port }}
  when: "'mosh' in ubuntu_common_optional_packages"

# TODO: port these logs  /var/log/auth.log, /var/log/syslog, and /var/log/messages.
