- name: Install postfix
  apt: name=postfix state=present

- name: ensure postfix is running
  service: name=postfix state=started enabled=yes
  
- name: Install mailutils
  apt: name=mailutils state=present

- name: Install postfix config
  template: src=main.cf.j2 dest=/etc/postfix/main.cf

- name: setup mail aliases # https://github.com/xcezx/ansible-aliases is another nice approach here
  template: src=aliases.j2 dest=/etc/aliases
  notify: update aliases database

- name: Set mailname
  template: src=mailname.j2 dest=/etc/mailname

- copy: src=./private/postfix-ssl/smtpd.crt dest=/etc/ssl/certs
- copy: src=./private/postfix-ssl/cacert.pem dest=/etc/ssl/certs
- copy: src=./private/postfix-ssl/smtpd.key dest=/etc/ssl/private/smtpd.key mode=0600 # VERY IMPORTANT THIS IS ONLY ROOT READABLE
  become_user: root # Belt and suspenders at this point, as we're running the system role as root already.

# TODO: make sure email is working. It doesn't seem to work locally
