- name: ensure postfix is running
  service: name=postfix state=started enabled=yes
  
- name: Install postfix config
  template: src=main.cf.j2 dest=/etc/postfix/main.cf

- name: setup mail aliases # https://github.com/xcezx/ansible-aliases is another nice approach here
  template: src=aliases.j2 dest=/etc/aliases
  notify: update aliases database

- name: Set mailname
  template: src=mailname.j2 dest=/etc/mailname

- copyv: src=./private/postfix-ssl/smtpd.crt dest=/etc/ssl/certs
- copyv: src=./private/postfix-ssl/cacert.pem dest=/etc/ssl/certs
- copyv: src=./private/postfix-ssl/smtpd.key dest=/etc/ssl/private/smtpd.key mode=0600 # VERY IMPORTANT THIS IS ONLY ROOT READABLE
  become_user: root # Belt and suspenders at this point, as we're running the system role as root already.

# TODO: make sure email is working. It doesn't seem to work locally
# helpful? https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml#L51

- name: Set up Postfix to relay mail
  debconf: name=postfix
           question='{{ item.question }}'
           value='{{ item.value }}'
           vtype='{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }
