# rsync config

- name: Ensure rsync conf file exists
  template: src=rsyncd.conf.j2 dest=/etc/rsyncd.conf

- name: update rsync default conf
  template: src=rsync-default.j2 dest=/etc/default/rsync

- name: ensure rsync is enabled
  service: name=rsync enabled=yes