---
- name: Ensure nginx is enabled
  become: yes
  become_user: root
  service:
    name: nginx
    state: started
    enabled: yes
  
- name: Ensure nginx conf exists
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx
  
- name: Ensure conf.d dir exists
  file:
    path: /etc/nginx/conf.d/
    state: directory
    mode: 0700

- name: Ensure nginx clojars conf exists
  template:
    src: clojars.nginx.conf.j2
    dest: /etc/nginx/conf.d/clojars.conf
  notify: reload nginx
  
- name: Ensure /var/log/nginx is world readable
  file:
    path: /var/log/nginx
    mode: 0755

- name: Ensure proper nginx lograte config exists
  template:
    src: logrotate-nginx.j2
    dest: /etc/logrotate.d/nginx
  
