- name: update aliases database
  command: newaliases
  become: yes

- name: reload postfix
  service: name=postfix state=reloaded

- name: restart rsync
  service: name=rsync state=restarted sleep=5

- name: restart sshd
  service: name=ssh state=restarted