# roles/openjdk1_8 - installs OpenJDK 1.8 for Ubuntu 14.04.x releases
# From https://github.com/curationexperts/ansible-hydra/blob/3b607347d795be77c6100691c8485b862f0e46c2/roles/openjdk1_8/tasks/main.yml
---
- name: ensure add-apt-repositories is present
  # sudo apt-get install software-properties-common
  become: yes
  apt: name=software-properties-common state=present
  
- name: add openjdk ppa
  # sudo add-apt-repository ppa:openjdk-r/ppa
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa' update_cache=yes

- name: install openjdk 1.8
  # sudo apt-get install openjdk-8-jdk
  become: yes
  apt: name=openjdk-8-jdk state=latest
  notify: update ca certificates
  
- name: select correct java version
  # sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  become: yes
  alternatives: name=java path=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

- name: select correct java compiler version
  # sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  become: yes
  alternatives: name=javac path=/usr/lib/jvm/java-8-openjdk-amd64/bin/javac
