ubuntu_common_required_packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - logwatch
  - ntp
  - postfix
  - mailutils

ubuntu_common_optional_packages:
  - mosh
  - vim

ubuntu_common_ssh_port: 22
ubuntu_common_mosh_from_port: 60000
ubuntu_common_mosh_to_port: 60010